Print manual registration command when the repository URL is undetermined
Some folks want to be able to use mr with local-only repositories but
don't necessarily know how to register those repositories, so this will
help inform them without performing a potentially incorrect action.

Factor out the full error message into a function
to reduce repetition within the mr register actions.

Fixes: https://bugs.debian.org/645965

diff --git a/mr b/mr
--- a/mr
+++ b/mr
@@ -2436,6 +2436,12 @@ ls = list
 [DEFAULT]
 order = 10
 lib =
+	url_error() {
+		info "cannot determine $* url"
+		info 'to register a local-only repository, run this:'
+		echo 'mr config "$(pwd)" checkout="error no url known for repo"' >&2
+		exit 1
+	}
 	error() {
 		echo "mr: $@" >&2
 		exit 1
@@ -2663,14 +2669,14 @@ git_register =
 	remote="$(LC_ALL=C git config --get branch.$branch.remote 2> /dev/null)" || remote=origin
 	url="`LC_ALL=C git config --get "remote.$remote.url"`" || true
 	if [ -z "$url" ]; then
-		error "cannot determine git url"
+		url_error git
 	fi
 	echo "Registering git url: $url in $MR_CONFIG"
 	mr -c "$MR_CONFIG" config "`pwd`" checkout="git clone '$url' '$MR_REPO'"
 bzr_register =
 	url="`LC_ALL=C bzr info . | egrep -i 'checkout of branch|parent branch' | awk '{print $NF}' | head -n 1`"
 	if [ -z "$url" ]; then
-		error "cannot determine bzr url"
+		url_error bzr
 	fi
 	echo "Registering bzr url: $url in $MR_CONFIG"
 	mr -c "$MR_CONFIG" config "`pwd`" checkout="bzr branch '$url' '$MR_REPO'"
@@ -2684,13 +2690,13 @@ cvs_register =
 	mr -c "$MR_CONFIG" config "`pwd`" checkout="cvs -d '$root' co -d '$MR_REPO' '$repo'"
 hg_register =
 	if ! url=`hg showconfig paths.default` ; then
-		error "cannot determine hg url"
+		url_error hg
 	fi
 	echo "Registering mercurial repo url: $url in $MR_CONFIG"
 	mr -c "$MR_CONFIG" config "`pwd`" checkout="hg clone '$url' '$MR_REPO'"
 darcs_register =
 	if ! url=`cat _darcs/prefs/defaultrepo 2> /dev/null` ; then
-		error "cannot determine darcs url"
+		url_error darcs
 	fi
 	echo "Registering darcs repository $url in $MR_CONFIG"
 	mr -c "$MR_CONFIG" config "`pwd`" checkout="darcs get '$url' '$MR_REPO'"
@@ -2699,7 +2705,7 @@ git_bare_register =
 	remote="$(LC_ALL=C GIT_CONFIG=config git config --get branch.$branch.remote 2> /dev/null)" || remote=origin
 	url="`LC_ALL=C GIT_CONFIG=config git config --get "remote.$remote.url"`" || true
 	if [ -z "$url" ]; then
-		error "cannot determine git url"
+		url_error git bare
 	fi
 	echo "Registering git url: $url in $MR_CONFIG"
 	mr -c "$MR_CONFIG" config "`pwd`" checkout="git clone --bare '$url' '$MR_REPO'"
@@ -2709,7 +2715,7 @@ vcsh_register =
 	remote="$(LC_ALL=C vcsh run "$mr_repo_basename" git config --get branch.$branch.remote 2> /dev/null)" || remote=origin
 	url="`LC_ALL=C vcsh run "$mr_repo_basename" git config --get "remote.$remote.url"`" || true
 	if [ -z "$url" ]; then
-		error "cannot determine git url"
+		url_error vcsh git
 	fi
 	echo "Registering git url: $url in $MR_CONFIG"
 	mr -c "$MR_CONFIG" config "`pwd`" checkout="vcsh clone '$url' '$mr_repo_basename'"
